apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/auth-depl.yaml
  - k8s/tickets-depl.yaml
  - k8s/orders-depl.yaml
  - k8s/payments-depl.yaml
  - k8s/expiration-depl.yaml
  - k8s/expiration-redis-depl.yaml
  - k8s/nats-depl.yaml
  - k8s/client-depl.yaml
  - k8s-prod/mongo-shared-depl.yaml
  - k8s-prod/client-config.yml
  - k8s-prod/ingress-srv.yaml
  - k8s-prod/cert-issuer.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-depl
      spec:
        template:
          spec:
            containers:
              - name: auth
                env:
                  - name: MONGO_URI
                    value: 'mongodb://mongo-srv:27017/auth'
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 250m
                    memory: 192Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 20
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tickets-depl
      spec:
        template:
          spec:
            containers:
              - name: tickets
                env:
                  - name: MONGO_URI
                    value: 'mongodb://mongo-srv:27017/tickets'
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 250m
                    memory: 192Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 20
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: orders-depl
      spec:
        template:
          spec:
            containers:
              - name: orders
                env:
                  - name: MONGO_URI
                    value: 'mongodb://mongo-srv:27017/orders'
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 250m
                    memory: 192Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 20
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: payments-depl
      spec:
        template:
          spec:
            containers:
              - name: payments
                env:
                  - name: MONGO_URI
                    value: 'mongodb://mongo-srv:27017/payments'
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 250m
                    memory: 192Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 20
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: expiration-depl
      spec:
        template:
          spec:
            containers:
              - name: expiration
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 250m
                    memory: 192Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: client-depl
      spec:
        template:
          spec:
            containers:
              - name: client
                resources:
                  requests:
                    cpu: 50m
                    memory: 96Mi
                  limits:
                    cpu: 300m
                    memory: 384Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 20
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nats-depl
      spec:
        template:
          spec:
            containers:
              - name: name
                resources:
                  requests:
                    cpu: 25m
                    memory: 32Mi
                  limits:
                    cpu: 150m
                    memory: 128Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: expiration-redis-depl
      spec:
        template:
          spec:
            containers:
              - name: expiration-redis
                resources:
                  requests:
                    cpu: 25m
                    memory: 32Mi
                  limits:
                    cpu: 150m
                    memory: 128Mi
