name: deploy-orders

on:
  push:
    branches: ["main"]
    paths: ["orders/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd orders && docker build -t ksburhan/orders .
      - run: docker login -u $DOCKER_USERNAME  -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ksburhan/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_SECRET }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl
